name: g_drive
description: A new Flutter project Clone Google-Drive App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  filesize: ^2.0.1
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.1.1
  google_fonts: ^4.0.4
  fl_chart: ^0.62.0
  flutter_screenutil: ^5.7.0
  intl: ^0.18.1
  page_transition: ^2.0.9
  percent_indicator: ^4.2.3
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
